### ISSUE TITLE
antipackets

### ISSUE THREAD

**Issue by enderson0** [AriliusClient/AntiAntiXray#1]
assign each (radius) to a (delay) so only 1 has to be modified and you never get packet kicked

**Comment by constantinDev** [comment]
idk what you exactly mean by that, but since we need to send a blockbreakingabort packet for each block in a radius to refresh it, we need the 3 loops for x, y and z. means you need (amount\*2)^3 packets sent, in every case. which will take (amount\*2)^3*delay milliseconds. We cant get around that.

**Comment by enderson0** [comment]
by this i meant
@aax setrange 10
sets delay to 10 or long enough to not get packet kicked
