### ISSUE TITLE
Doesn't seem to work with NCP (or whatever Ore Obfuscator plugin is being used)

### ISSUE THREAD

**Issue by ggtylerr** [AriliusClient/AntiAntiXray#11]
Tried it on this server: mc.shadowkingdom.org

The plugin they're using is NCP. The might have some additional anti-xray plugin that I didn't recognize.

It doesn't seem to work when I test it out. [Here's a video of that.](https://i.vgy.me/VNmXAd.webm) (Cropped it so it doesn't include the coordinates. Radius was set to 10.)

**Comment by constantinDev** [comment]
uh oh, that seems as if some plugin is blocking the packets from actually doing anything. It cant be ncp, since i tested it on servers with ncp, it seems to be the antixray plugin. I cant do anything about that yet, sorry.

**Comment by ggtylerr** [comment]
Damn :/

Well, if it helps, here's a list of plugins they're using:

<details>
<summary>Plugins</summary>

advancedachievements, advancedenchantments, advancedregionmarket, advancedsets, aegive, alchemist, antiadvertiser, antiworldfly, apply, armorstandtools, autorestart, backpack, betterconcrete, bkcommonlib, blueholo, bossshoppro, bukkit, buycraftx, chatreaction, chestcleaner, chestshop, citizens, clearinventory, commandnpc, compatnocheatplus, conditionalcommands, coreprotect, crazyauctions, crazycrates, crazyenvoy, customjoinmessages, discordsrv, disposal, elevator, enchanter, entitytrackerfixer, epicrename, essentials, essentialsspawn, ezauctions, farmlimiter, gsit, headdatabase, holographicdisplays, item2chat, jobs, lagassist, lightcleaner, limitpillagers, litebans, lottery, luckperms, lwc, lwckeys, mcmmo, minecraft, multiverse—core, mycommand, mypet, mywarp, nametagedit, nerfphantoms, nocheatplus, paper, placeholderapi, plugman, protocollib, pvpmanager, pwnfilter, randomteleport, rayexport, reportrts, selectionvisualizer, shadowconnect, shadowemote, shadowhunger, shadownamefixer, shadowspeed, shadowtowns, spark, spigot, superbvote, supertrails, taxes, tinkerer, titlemanager, towny, townygui, tradeplus, ultimateannounce, vault, venturechat, viaversion, voteparty, vouchers, voxel_sniper, wildstacker, worldborder, worldedit, worldguard

</details>
